<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Overimagined.ZLoggerColorConsole" Version="1.0.0" />
    <PackageReference Include="ZLogger" Version="2.5.10" />
  </ItemGroup>

</Project>
